

DATABASE ="ESCRIBA EL NOMBRE DE LA BASE DE DATOS"
USER = "ESCRIBA EL USUARIO DE LA DB"
PASSWORD = "ESCRIBA LA CONTRASEÑA"
HOST = "ESCRIBA LA DIRECCION DNS O DIRECCION IP DEL SERVIDOR"
PORT = 5432 # POR DEFECTO ES 5432, PERO PUEDE CAMBIAR EN SU DB